// Champion data with IDs - only active champions for pick/ban
export interface Champion {
  id: number;
  name: string;
  key: string;
}

// Liste des champions populaires/courants (tu peux compléter avec l'API DDragon si besoin)
export const CHAMPIONS: Champion[] = [
  { id: 266, name: "Aatrox", key: "Aatrox" },
  { id: 103, name: "Ahri", key: "Ahri" },
  { id: 84, name: "Akali", key: "Akali" },
  { id: 166, name: "Akshan", key: "Akshan" },
  { id: 12, name: "Alistar", key: "Alistar" },
  { id: 32, name: "Amumu", key: "Amumu" },
  { id: 34, name: "Anivia", key: "Anivia" },
  { id: 1, name: "Annie", key: "Annie" },
  { id: 523, name: "Aphelios", key: "Aphelios" },
  { id: 22, name: "Ashe", key: "Ashe" },
  { id: 136, name: "Aurelion Sol", key: "AurelionSol" },
  { id: 893, name: "Aurora", key: "Aurora" },
  { id: 268, name: "Azir", key: "Azir" },
  { id: 432, name: "Bard", key: "Bard" },
  { id: 200, name: "Bel'Veth", key: "Belveth" },
  { id: 53, name: "Blitzcrank", key: "Blitzcrank" },
  { id: 63, name: "Brand", key: "Brand" },
  { id: 201, name: "Braum", key: "Braum" },
  { id: 233, name: "Briar", key: "Briar" },
  { id: 51, name: "Caitlyn", key: "Caitlyn" },
  { id: 164, name: "Camille", key: "Camille" },
  { id: 69, name: "Cassiopeia", key: "Cassiopeia" },
  { id: 31, name: "Cho'Gath", key: "Chogath" },
  { id: 42, name: "Corki", key: "Corki" },
  { id: 122, name: "Darius", key: "Darius" },
  { id: 131, name: "Diana", key: "Diana" },
  { id: 119, name: "Draven", key: "Draven" },
  { id: 36, name: "Dr. Mundo", key: "DrMundo" },
  { id: 245, name: "Ekko", key: "Ekko" },
  { id: 60, name: "Elise", key: "Elise" },
  { id: 28, name: "Evelynn", key: "Evelynn" },
  { id: 81, name: "Ezreal", key: "Ezreal" },
  { id: 9, name: "Fiddlesticks", key: "Fiddlesticks" },
  { id: 114, name: "Fiora", key: "Fiora" },
  { id: 105, name: "Fizz", key: "Fizz" },
  { id: 3, name: "Galio", key: "Galio" },
  { id: 41, name: "Gangplank", key: "Gangplank" },
  { id: 86, name: "Garen", key: "Garen" },
  { id: 150, name: "Gnar", key: "Gnar" },
  { id: 79, name: "Gragas", key: "Gragas" },
  { id: 104, name: "Graves", key: "Graves" },
  { id: 887, name: "Gwen", key: "Gwen" },
  { id: 120, name: "Hecarim", key: "Hecarim" },
  { id: 74, name: "Heimerdinger", key: "Heimerdinger" },
  { id: 910, name: "Hwei", key: "Hwei" },
  { id: 420, name: "Illaoi", key: "Illaoi" },
  { id: 39, name: "Irelia", key: "Irelia" },
  { id: 427, name: "Ivern", key: "Ivern" },
  { id: 40, name: "Janna", key: "Janna" },
  { id: 59, name: "Jarvan IV", key: "JarvanIV" },
  { id: 24, name: "Jax", key: "Jax" },
  { id: 126, name: "Jayce", key: "Jayce" },
  { id: 202, name: "Jhin", key: "Jhin" },
  { id: 222, name: "Jinx", key: "Jinx" },
  { id: 145, name: "Kai'Sa", key: "Kaisa" },
  { id: 429, name: "Kalista", key: "Kalista" },
  { id: 43, name: "Karma", key: "Karma" },
  { id: 30, name: "Karthus", key: "Karthus" },
  { id: 38, name: "Kassadin", key: "Kassadin" },
  { id: 55, name: "Katarina", key: "Katarina" },
  { id: 10, name: "Kayle", key: "Kayle" },
  { id: 141, name: "Kayn", key: "Kayn" },
  { id: 85, name: "Kennen", key: "Kennen" },
  { id: 121, name: "Kha'Zix", key: "Khazix" },
  { id: 203, name: "Kindred", key: "Kindred" },
  { id: 240, name: "Kled", key: "Kled" },
  { id: 96, name: "Kog'Maw", key: "KogMaw" },
  { id: 897, name: "K'Sante", key: "KSante" },
  { id: 7, name: "LeBlanc", key: "Leblanc" },
  { id: 64, name: "Lee Sin", key: "LeeSin" },
  { id: 89, name: "Leona", key: "Leona" },
  { id: 876, name: "Lillia", key: "Lillia" },
  { id: 127, name: "Lissandra", key: "Lissandra" },
  { id: 236, name: "Lucian", key: "Lucian" },
  { id: 117, name: "Lulu", key: "Lulu" },
  { id: 99, name: "Lux", key: "Lux" },
  { id: 54, name: "Malphite", key: "Malphite" },
  { id: 90, name: "Malzahar", key: "Malzahar" },
  { id: 57, name: "Maokai", key: "Maokai" },
  { id: 11, name: "Master Yi", key: "MasterYi" },
  { id: 902, name: "Milio", key: "Milio" },
  { id: 21, name: "Miss Fortune", key: "MissFortune" },
  { id: 62, name: "Wukong", key: "MonkeyKing" },
  { id: 82, name: "Mordekaiser", key: "Mordekaiser" },
  { id: 25, name: "Morgana", key: "Morgana" },
  { id: 950, name: "Naafiri", key: "Naafiri" },
  { id: 267, name: "Nami", key: "Nami" },
  { id: 75, name: "Nasus", key: "Nasus" },
  { id: 111, name: "Nautilus", key: "Nautilus" },
  { id: 518, name: "Neeko", key: "Neeko" },
  { id: 76, name: "Nidalee", key: "Nidalee" },
  { id: 895, name: "Nilah", key: "Nilah" },
  { id: 56, name: "Nocturne", key: "Nocturne" },
  { id: 20, name: "Nunu & Willump", key: "Nunu" },
  { id: 2, name: "Olaf", key: "Olaf" },
  { id: 61, name: "Orianna", key: "Orianna" },
  { id: 516, name: "Ornn", key: "Ornn" },
  { id: 80, name: "Pantheon", key: "Pantheon" },
  { id: 78, name: "Poppy", key: "Poppy" },
  { id: 555, name: "Pyke", key: "Pyke" },
  { id: 246, name: "Qiyana", key: "Qiyana" },
  { id: 133, name: "Quinn", key: "Quinn" },
  { id: 497, name: "Rakan", key: "Rakan" },
  { id: 33, name: "Rammus", key: "Rammus" },
  { id: 421, name: "Rek'Sai", key: "RekSai" },
  { id: 526, name: "Rell", key: "Rell" },
  { id: 888, name: "Renata Glasc", key: "Renata" },
  { id: 58, name: "Renekton", key: "Renekton" },
  { id: 107, name: "Rengar", key: "Rengar" },
  { id: 92, name: "Riven", key: "Riven" },
  { id: 68, name: "Rumble", key: "Rumble" },
  { id: 13, name: "Ryze", key: "Ryze" },
  { id: 360, name: "Samira", key: "Samira" },
  { id: 113, name: "Sejuani", key: "Sejuani" },
  { id: 235, name: "Senna", key: "Senna" },
  { id: 147, name: "Seraphine", key: "Seraphine" },
  { id: 875, name: "Sett", key: "Sett" },
  { id: 35, name: "Shaco", key: "Shaco" },
  { id: 98, name: "Shen", key: "Shen" },
  { id: 102, name: "Shyvana", key: "Shyvana" },
  { id: 27, name: "Singed", key: "Singed" },
  { id: 14, name: "Sion", key: "Sion" },
  { id: 15, name: "Sivir", key: "Sivir" },
  { id: 72, name: "Skarner", key: "Skarner" },
  { id: 901, name: "Smolder", key: "Smolder" },
  { id: 37, name: "Sona", key: "Sona" },
  { id: 16, name: "Soraka", key: "Soraka" },
  { id: 50, name: "Swain", key: "Swain" },
  { id: 517, name: "Sylas", key: "Sylas" },
  { id: 134, name: "Syndra", key: "Syndra" },
  { id: 223, name: "Tahm Kench", key: "TahmKench" },
  { id: 163, name: "Taliyah", key: "Taliyah" },
  { id: 91, name: "Talon", key: "Talon" },
  { id: 44, name: "Taric", key: "Taric" },
  { id: 17, name: "Teemo", key: "Teemo" },
  { id: 412, name: "Thresh", key: "Thresh" },
  { id: 18, name: "Tristana", key: "Tristana" },
  { id: 48, name: "Trundle", key: "Trundle" },
  { id: 23, name: "Tryndamere", key: "Tryndamere" },
  { id: 4, name: "Twisted Fate", key: "TwistedFate" },
  { id: 29, name: "Twitch", key: "Twitch" },
  { id: 77, name: "Udyr", key: "Udyr" },
  { id: 6, name: "Urgot", key: "Urgot" },
  { id: 110, name: "Varus", key: "Varus" },
  { id: 67, name: "Vayne", key: "Vayne" },
  { id: 45, name: "Veigar", key: "Veigar" },
  { id: 161, name: "Vel'Koz", key: "Velkoz" },
  { id: 711, name: "Vex", key: "Vex" },
  { id: 254, name: "Vi", key: "Vi" },
  { id: 234, name: "Viego", key: "Viego" },
  { id: 112, name: "Viktor", key: "Viktor" },
  { id: 8, name: "Vladimir", key: "Vladimir" },
  { id: 106, name: "Volibear", key: "Volibear" },
  { id: 19, name: "Warwick", key: "Warwick" },
  { id: 498, name: "Xayah", key: "Xayah" },
  { id: 101, name: "Xerath", key: "Xerath" },
  { id: 5, name: "Xin Zhao", key: "XinZhao" },
  { id: 157, name: "Yasuo", key: "Yasuo" },
  { id: 777, name: "Yone", key: "Yone" },
  { id: 83, name: "Yorick", key: "Yorick" },
  { id: 350, name: "Yuumi", key: "Yuumi" },
  { id: 154, name: "Zac", key: "Zac" },
  { id: 238, name: "Zed", key: "Zed" },
  { id: 221, name: "Zeri", key: "Zeri" },
  { id: 115, name: "Ziggs", key: "Ziggs" },
  { id: 26, name: "Zilean", key: "Zilean" },
  { id: 142, name: "Zoe", key: "Zoe" },
  { id: 143, name: "Zyra", key: "Zyra" },
];

export function getChampionById(id: number): Champion | undefined {
  return CHAMPIONS.find((champ) => champ.id === id);
}

export function getChampionByName(name: string): Champion | undefined {
  return CHAMPIONS.find((champ) => champ.name.toLowerCase() === name.toLowerCase());
}
